### ISSUE TITLE
Tile request returns 200 when using invalid map.

### ISSUE THREAD

**Issue by jamesyarrington** [terranodo/tegola#250] opened 2018-01-04 19:28 UTC
**To Reproduce:**
Send a GET request to `/maps/foo/1/1/1.pbf`

**Expected Response:**
The response is coded as a `400 Bad Request` or `404 Not Found`, with an appropriate message, like:
> map (foo) not configured ...

**Actual Response:**
Response is coded as `200 OK`.
The file `1.pbf` is downloaded, which contains the message:
> map (foo) not configured. check your config file

The response should be an error code, and the error message should not be downloaded like a file, it should simply be a response body.

**Comment by ARolek** [comment] 2018-01-04 19:34
@jamesyarrington what version of tegola are you using? I looked at the code and the server should be handling it fine.

**Comment by ARolek** [comment] 2018-01-04 22:55
This is caused by the tile cache middleware. On the first request the response is correct, but the middleware is not sniffing for a 200 and writes to the cache anyway. Subsequent requests then read from the cache which causes the 200 response.

**Comment by ARolek** [comment] 2018-01-05 17:48
This has been fixed in the v0.6.0 branch.

**Closed by ARolek** 2018-01-05 17:48 UTC
Labels: bug
