### ISSUE TITLE
Geometry clipping

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#56] opened 2016-08-03 00:30 UTC
Possible algos:
- [Efficient Parallel and Distributed Algorithms for
  GIS Polygon Overlay Processing](http://scholarworks.gsu.edu/cgi/viewcontent.cgi?article=1099&context=cs_diss)
- [Vatti clipping algorithm](https://en.wikipedia.org/wiki/Vatti_clipping_algorithm)
  [p56-vatti.pdf](https://github.com/terranodo/tegola/files/402456/p56-vatti.pdf)

**Comment by ARolek** [comment] 2016-08-05 03:22
@gdey 
![img_0908](https://cloud.githubusercontent.com/assets/667850/17425357/329f7572-5a81-11e6-952a-50c1a61fcb5b.JPG)

**Comment by gdey** [comment] 2017-01-22 05:18
Quick update. Have clipping working for most tiles. However, there are a few polygons that get clipped to nothing, that I believe should not be. 

As you can see from the missing tile:
![screen shot 2017-01-21 at 9 14 28 pm](https://cloud.githubusercontent.com/assets/14805/22180214/0cfc6bee-e01f-11e6-8449-df7bd4dd17c0.png)

I'm currently working on tooling to help me debug what is going on here. Once this is solved, clipping will be merged in for fuller testing. Initially, we will be rolling it out disabled.  Enabled the setting by setting the environment variable `TEGOLA_CLIPPING` to *yes*.

**Comment by ARolek** [comment] 2017-02-17 07:28
@gdey I was able to extract the geometries from the OSM database that were causing clipping issues as shown in the following screen shots:

<img width="919" alt="screen shot 2017-02-16 at 11 10 55 pm" src="https://cloud.githubusercontent.com/assets/667850/23056242/5683c76e-f49f-11e6-9a75-2a26e4bd3818.png">
<img width="381" alt="screen shot 2017-02-16 at 10 56 37 pm" src="https://cloud.githubusercontent.com/assets/667850/23056248/5e00f9a8-f49f-11e6-94a0-dfc9feff70a3.png">

Using the following SQL

```sql
SELECT
  ST_AsBinary(geometry) AS geometry, 
  id, 
  osm_id, 
  name, 
  type 
FROM 
  osm_waterways 
WHERE 
  geometry && ST_MakeEnvelope(254382.43009765446,5310233.228288574,256828.4150024396,5307787.243383789)
```

The attached output has 3 geometries in WKB format with their accompanying attributes.

[osm-waterway-output.txt](https://github.com/terranodo/tegola/files/782540/osm-waterway-output.txt)

**Comment by ARolek** [comment] 2017-02-19 03:41
One more isolated test case
<img width="890" alt="screen shot 2017-02-18 at 7 35 51 pm" src="https://cloud.githubusercontent.com/assets/667850/23099035/2eb07286-f612-11e6-8978-79b0dbc5e2a8.png">

Using the following SQL

```sql
SELECT 
  id, 
  osm_id, 
  name, 
  type, 
  ST_AsBinary(geometry) AS geometry
FROM 
  osm_roads
WHERE 
  geometry && ST_MakeEnvelope(-1.3644926791343994e+07,5.657563084768066e+06,-1.3644315295117797e+07,5.65695158854187e+06)
```

The attached output has 2 geometries in WKB format with their accompanying attributes.

[osm-roads-output.txt](https://github.com/terranodo/tegola/files/785518/osm-roads-output.txt)

**Comment by allspatial** [comment] 2017-03-04 00:37
Hi @ARolek and @gdey, I am getting the same type of errors with my line layers frequently. I am also getting (occasionally) the polygon error described by @gdey above, so whole tiles would be completely missing from my map. If I can help with anything (logged SQL statements, etc.) to solve that issue faster please let me know. The clipping issue is the main reason that prevents me from going fully live with my page currently. I would provide a link early next week after updating my server so you can test on my mapbox-gl-js application/page if this is of help. Many thanks for your great efforts!

**Comment by gdey** [comment] 2017-03-04 01:03
Hi @allspatial !

Have you tried the latest build from this branch? I push up a few more fixes late last night. Also, be aware that by default the clipping is turned off and you have to setting the environmental variable TEGOLLA_CLIPPING to mvt, `TEGOLA_CLIPPING="mvt"` not to yes as I had in said in a different comment.

I'm looking into more bugs that @ARolek ARolek has pointed out to me. I, also, have pushed out a small utility to help me get test cases. I'll write up a quick usage guide for it after I make some improvements to make generating the test cases easier.

**Comment by allspatial** [comment] 2017-03-04 01:11
Hi @gdey, thanks for your swift reply! The changes from last night I haven't tried yet. Will do so right now. The "mvt" I already figured out.

**Comment by allspatial** [comment] 2017-03-05 05:38
Hi @gdey, I tested the latest clipping_3 branch. Line clipping seems to work better now, polygons still disappear (see screenshot). And I can now see the tile boundaries, I assume you are showing them for testing purposes. Many thanks!
![shot](https://cloud.githubusercontent.com/assets/12534211/23584858/6291c502-0187-11e7-9d86-929b219e1dc3.png)

**Comment by gdey** [comment] 2017-03-06 03:17
@allspatial No, those gray lines should not be there. I think I have to increase the overlap buffer for that. I've got a few more fix coming with a new push. 

Thank you for looking into this.

**Comment by allspatial** [comment] 2017-03-14 17:03
Hi @gdey and @ARolek, issues #90, #100 and #56 could probably be merged since they all refer to the clipping. It would reduce the number of issues at once without much effort ;-). Taking into account also issue #102 which would be the recommended Tegola version to test now with regard to improved geometry clipping and MVT specification compliance? By the way, here is the link to the application I am working on, just to have another test case:
[https://www.webgis.gov.sc/mobile/](https://www.webgis.gov.sc/mobile/)

Thanks again!

**Comment by allspatial** [comment] 2017-04-07 04:20
Hi @gdey, I just pulled and tested the latest v0.4.0 branch. The line clipping works much better and there are no fictive lines anymore crossing the screen. However, there is one issue I found where a part of the line would be completely missing (screenshot "shot3" attached). Regarding the polygons I still get the issue of tiles completely missing. And currently I am seeing the tile boundaries. Many thanks!!
![shot1](https://cloud.githubusercontent.com/assets/12534211/24785450/fa1baf62-1b6a-11e7-8570-f2b752136dd0.png)
![shot2](https://cloud.githubusercontent.com/assets/12534211/24785451/fa70c704-1b6a-11e7-8e3c-e64dd7cecc10.png)
![shot3](https://cloud.githubusercontent.com/assets/12534211/24785452/fa79546e-1b6a-11e7-966e-656cbec01aec.png)

**Comment by ARolek** [comment] 2017-04-10 16:10
@allspatial thanks for testing out the v0.4.0 branch and providing the screen shots. We have a lot of effort going into clipping right now and we believe we have identified the clipping issues you're showing screenshots 1 and 2. The primary issue has to do with scaling and what happens to the geometries at lower zoom levels. After scaling the geometries can become invalid which causes the clipping algorithm fail in certain situations (as you're seeing). For the most part we only see the issue at low zooms. Do you see issues when zoomed in?

The second issue has to do with our tile buffer which we're also working on. The tile buffer needs to extend past the tile extent to ensure smooth transitions from tile to tile. We're already on it and hope to have a solution soon. Would you like me to ping you next time the v0.4.0 branch is updated?

**Comment by gdey** [comment] 2017-04-10 16:26
@allspatial Thanks for the update. I found some issues with the way I have been doing things, that is requiring a deeper change. So, I am working through that change right now. 

The issue with the borders is because my buffer zone around the title is not large enough. I will be increasing that as soon as I get better handle of the clipping.

One of the issue is that once we scale the polygons to the the correct zoom level. The polygon becomes invalid, the clipping also expects valid polygons (concave, non-intersecting) so it ends up not clipping things correctly.

![blank](https://cloud.githubusercontent.com/assets/14805/24871739/8309d6bc-1dcf-11e7-9901-244159b72eeb.png)


I'm working through these things.

Thank you for all the info.

**Comment by allspatial** [comment] 2017-04-11 04:20
Hi @ARolek and @gdey, many thanks for your efforts! The issue with the missing tiles for the polygon layer I also get at higher zoom levels. And yes, please let me know once the v0.4.0 branch has been updated. However, I am frequently checking anyway ;-). Thanks again!!!

**Comment by gdey** [comment] 2017-04-13 18:30
@allspatial Just pushed up some more changes to the v0.4.0 branch. Let me know if that works better. It is slower, and will work on speeding things up once I have things working correctly.

**Comment by allspatial** [comment] 2017-04-15 17:36
Ho @gdey, much better now! Lines look all good and tile boundaries don't show anymore. The only remaining issue is the tiles for polygon layers that are still missing sometimes. Many thanks!
![shot](https://cloud.githubusercontent.com/assets/12534211/25065593/8e004f1c-2223-11e7-833d-f37c431077ec.png)

**Comment by jj0hns0n** [comment] 2017-04-15 17:43
@arolek is this the same thing we see at low zo in the OSM

**Comment by ARolek** [comment] 2017-04-17 17:58
@allspatial thanks again for the tests. What zoom level are you at? Also we have a new tool that can dump WKB for our test suite. @gdey would it be helpful to have a dump of the tile for a test case?

**Comment by allspatial** [comment] 2017-04-18 16:33
Hi @ARolek and @gdey , I observed the issue at zoom levels 12 to 16 mostly in my case:
[Seychelles WebGIS](https://www.webgis.gov.sc/mobile/)

And yes, let me know if you need a geometry dump.
Many thanks!

**Comment by allspatial** [comment] 2017-05-04 21:12
Hi @gdey and @ARolek, after updating to the latest v0.4.0 version it seems the number of geometry issues has increased again. mapbox-gl-js also shows a warning that the tiles are not tile spec v2 conform which could cause rendering issues. I can't tell though how serious this warning is and if it really causes some of the issues you can see in the attached screenshots or if all results from the clipping. Many thanks!
![shot1](https://cloud.githubusercontent.com/assets/12534211/25725106/a39e1ffa-312f-11e7-9d48-146c27d99559.png)
![shot2](https://cloud.githubusercontent.com/assets/12534211/25725107/a3fd0c36-312f-11e7-8b70-09602cde038a.png)

**Comment by allspatial** [comment] 2017-05-05 04:59
Hi @ARolek, many thanks for the clarification! That sounds all good and I am very much looking forward. Tegola is a great tool and with the clipping fixed it will be perfect ;-).

**Comment by allspatial** [comment] 2017-06-05 00:49
Hi @ARolek and @gdey, did you by chance find the time to do some refactoring/improvement on the clipping part? If so - in what branch would I find that? With the current version of v0.4.0 I can't go live (see attached). Many thanks!!!
![shot](https://cloud.githubusercontent.com/assets/12534211/26766850/5eb8db3a-49c3-11e7-9b26-819bc035e9b3.png)

**Comment by ARolek** [comment] 2017-06-05 01:30
@allspatial we have some major clipping improvements coming queued up. Hoping to merge into his ranch next week. In the mean time I think what you're seeing is the clipping is not turned on. Can you check if the environment var TEGOLA_CLIPPING="mvt" is set?

**Comment by allspatial** [comment] 2017-06-05 14:08
Hi @ARolek, I indeed forgot to set the clipping parameter this time. I apologise for the "false alarm".

**Comment by gdey** [comment] 2017-06-05 21:32
@allspatial No worries, always appreciate people keeping an eye out for possible regressions. I've got more changes, coming. Need to push up the changes I have from last week to the issue-56 branch( https://github.com/terranodo/tegola/tree/issue-56 ). I have gotten few more fixes. I'm still seeing issues that I am working through one by one.

**Comment by gdey** [comment] 2017-06-09 07:43
@allspatial Hey I have the latest version of the clipping code pushed to issue_56 branch. Be warned it's slow now, and I have to go through a round of optimizations. I believe I have it clipping most things correctly now. At least things looked good when I did a quick skim. 

I have not had a chance to zoom around the global map searching for issues.

**Comment by Wykks** [comment] 2017-06-09 08:45
Hi !
Thanks you for this software !
I have the same issue as allspatial, I'm gettings something like this (https://github.com/terranodo/tegola/issues/56#issuecomment-306079317) in the master branch.

I tried the issue-56 branch (with and without your latest changes) and it's worse, nothing appears, even with TEGOLA_CLIPPING="mvt". How can I help to debug this ?

**Comment by gdey** [comment] 2017-06-09 08:57
@Wykks Could you post an image. Also, with my latest changes, it takes a long while to generate the tiles. The reason being the validation process checks every segment in a feature against every other segment in that feature to make sure that no two segments that are not direct neighbors cross.  The crossing can occur after simplification — this was the source of some of the clipping issues. I will be profiling and see how I can speed this up as it's unusable at current. I am trying to get clipping correct first before optimizing it.

**Comment by Wykks** [comment] 2017-06-09 09:05
Sure !

With issue-56 without TEGOLA_CLIPPING="mvt" : 
![image](https://user-images.githubusercontent.com/1236069/26968541-a95b630a-4d02-11e7-9576-7ca8df80cd78.png)
With issue-56 with TEGOLA_CLIPPING="mvt" : 
![image](https://user-images.githubusercontent.com/1236069/26968562-b8e0d5bc-4d02-11e7-8f1e-5b60a787ddf9.png)
With master : 
![image](https://user-images.githubusercontent.com/1236069/26968613-f91a8768-4d02-11e7-8ae0-f9a50bc55e61.png)
With master + zoom : 
![image](https://user-images.githubusercontent.com/1236069/26968766-7ba645be-4d03-11e7-86a7-ebeba7856fc6.png)
(Mapbox-gl only, work fine with leaflet)

Data used : https://github.com/gregoiredavid/france-geojson/blob/master/departements.geojson (imported to postgis with ogr2ogr)

**Comment by gdey** [comment] 2017-06-09 09:14
@Wykks Thanks! I'll take a look at it later today. I really need to get some sleep. :P

**Comment by skinkie** [comment] 2017-08-20 20:11
#132 seem to show the same issue. At mapbox the suggestion is done that it is due to the 'buffer-size' of the tiles. Would that ring a bell?

**Comment by skinkie** [comment] 2017-08-20 20:19
Please take a peak at this comment:
https://github.com/mapbox/mapbox-gl-js/issues/5175#issuecomment-323609118

**Comment by gdey** [comment] 2017-11-01 20:33
This is now done.

**Closed by gdey** 2017-11-01 20:33 UTC
Labels: feature
