### ISSUE TITLE
Support for DATABASE_URL environment variable

### ISSUE THREAD

**Issue by mojodna** [terranodo/tegola#137] opened 2017-08-27 23:05 UTC
In addition to specifying database credentials in the `[[providers]]` section of the config TOML, `DATABASE_URL` should be read (as a URI), allowing configuration files to be freely hosted and shared without concern for leaking secrets.

E.g., `postgis://tegola:<redacted>@<redacted>:5432/osm` (and/or `postgresql` for compatibility with `libpq`).

**Comment by ARolek** [comment] 2017-08-31 01:28
Just to clarify, you're suggesting we read in an environment variable into a "template variable" defined in the config? I like this idea as it could support multiple database URIs when the config is working with several data providers.

**Comment by mojodna** [comment] 2017-08-31 01:31
Yes, I think we're talking about the same thing as long as only 1 set of database credentials is in use.

The goal is to remove the database credentials from the config and have them dynamically added by the server.

**Comment by ARolek** [comment] 2017-09-13 23:36
This is related to #77

**Comment by ARolek** [comment] 2017-09-13 23:36
And it looks like a dupe of #95

**Closed by ARolek** 2017-09-13 23:36 UTC
