### ISSUE TITLE
When setting table using a mixture of upper and lowercase letters, the table can not be found

### ISSUE THREAD

**Issue by donnyv** [terranodo/tegola#116] opened 2017-04-20 06:25 UTC
It looks like the table name is being converted to lowercase and then sent to Postgres. It shouldn't touch the casing since there could be caps involved.

**Comment by ARolek** [comment] 2017-04-24 16:54
@donnyv thanks for the report. I'm going to mark this as a bug and will work on a fix.

**Comment by ARolek** [comment] 2017-05-02 00:31
@donnyv I'm not able to recreate this issue. I wonder if the problem is elsewhere? We have a debug flag which can be helpful in this situation. Try running

```bash
SQL_DEBUG=EXECUTE_SQL tegola --config=/path/to/config.toml
```
This will print out the SQL statements as they will be sent to PostGIS. 

Here's an example of the layer config I was testing. Notice the casing on builDINGS. This carried through all the way to the execute statements send to the database.

```toml
[[providers.layers]]
name = "building"
geometry_fieldname = "wkb_geometry"
id_fieldname = "ogc_fid"
srid=4326
sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM builDINGS WHERE wkb_geometry && !BBOX!"
```

**Comment by ARolek** [comment] 2017-05-05 15:23
I'm closing this issue for now. @donnyv if you have a chance to test out the debug command or find an alternative way to recreate this issue I'm happy to revisit it.

**Closed by ARolek** 2017-05-05 15:23 UTC
Labels: bug
